// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatsListController from "./chats_list_controller"
application.register("chats-list", ChatsListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InputResizeController from "./input_resize_controller"
application.register("input-resize", InputResizeController)
