// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatsListController from "./chats_list_controller"
application.register("chats-list", ChatsListController)

import ComposerController from "./composer_controller"
application.register("composer", ComposerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
